annotations:
  catalog.cattle.io/rancher-version: <2.5.99-0
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Longhorn
  catalog.cattle.io/namespace: longhorn-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/provides-gvr: longhorn.io/v1beta1
  catalog.cattle.io/release-name: longhorn
  catalog.cattle.io/ui-component: longhorn
apiVersion: v1
name: longhorn
version: 1.2.3
appVersion: v1.2.3
kubeVersion: ">=1.18.0-0"
description: Longhorn is a distributed block storage system for Kubernetes.
keywords:
- longhorn
- storage
- distributed
- block
- device
- iscsi
- nfs
home: https://github.com/longhorn/longhorn
sources:
- https://github.com/longhorn/longhorn
- https://github.com/longhorn/longhorn-engine
- https://github.com/longhorn/longhorn-instance-manager
- https://github.com/longhorn/longhorn-share-manager
- https://github.com/longhorn/longhorn-manager
- https://github.com/longhorn/longhorn-ui
- https://github.com/longhorn/longhorn-tests
- https://github.com/longhorn/backing-image-manager
maintainers:
- name: Longhorn maintainers
  email: maintainers@longhorn.io
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
